# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  alphen.co.za:
    site_hosts:
    - canonical: www.alphen.co.za
      redirects:
      - alphen.co.za
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
